#!/bin/bash 
date="$(date)";
(git add . && git commit -m "$date") &>/dev/null &
gcc -o "out/ml" ml.c lib/plib.c # -lavcodec -lavformat -lavutil -lswscale -lX11 -Wall -lXext
git push &>/dev/null &
"./out/ml" $@
